version: "3"

services:
  api:
    container_name: api
    build: ./plugin-store-api
    ports:
      - "5100:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=shopuser
      - DB_PASS=qwerty123
      - DB_NAME=plugin-store
      - WP_DB_NAME=wordpress
      - JWT_SECRET=vZiXOo3r7IgFtLh3TVtuiKxVtXfqMlAs
      - LICENSE_URL=http://192.168.10.46:10100
      - WOOCOMMERCE_API_URL=http://wordpress
      - WOOCOMMERCE_JWT=eyJhbGciOiJIUzI1NiJ9.e30.IcewD6aHHneV8OmlYIjUYpeOQglvBQ1gK7o51Lfp7xo
  
  wordpress:
    container_name: wordpress
    image: wordpress:6.1.1
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=shopuser
      - WORDPRESS_DB_PASSWORD=qwerty123
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./data/wordpress:/var/www/html
      - ./data/restly:/var/www/html/wp-content/themes/restly
      - ./data/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=plugin-store
      - MYSQL_USER=shopuser
      - MYSQL_PASSWORD=qwerty123
      - MYSQL_ROOT_PASSWORD=qwerty123
    volumes:
      - ./data/db:/var/lib/mysql
  
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
